version: '3.9'

networks:
  ps-sonar:
    external: true

services:
  sonarweb:
    image: sonarqube:latest
    container_name: ${SONAR_WEB_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    networks:
      - ps-sonar
    volumes:
      - /home/docker/${SONAR_WEB_CONTAINER_NAME}/data:/opt/sonarqube/data
      - /home/docker/${SONAR_WEB_CONTAINER_NAME}/logs:/opt/sonarqube/logs
      - /home/docker/${SONAR_WEB_CONTAINER_NAME}/extensions:/opt/sonarqube/extensions
    ports:
      - "47005:9000"
    environment:
      SONAR_JDBC_USERNAME: ${SONAR_DB_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_DB_USERPASSWORD}
      SONAR_JDBC_URL: jdbc:sqlserver://${SONAR_DB_CONTAINER_NAME}:1433;databaseName=${SONAR_DB_DATABASE_NAME};encrypt=false;
