version: '3.9'

services:
  redis:
    container_name: ${CONTAINER_NAME}
    image: redis:${REDIS_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '{PUBLIC_PORT_6379}:6379'
    volumes:
      - /home/dockervolumes/${CONTAINER_NAME}/data:/data
      - '/redis.conf:/usr/local/etc/redis/redis.conf'
