version: '3.9'

networks:
  ps-sql-net:
    external: true
    
services:
  mssql:
    # Limits
    cpus: 1.0
    mem_reservation: "1024M"
    mem_limit: "2048M"
    image: mcr.microsoft.com/mssql/server:${MSSQL_IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    networks:
      - ps-sql-net
    ports:
      - ${PUBLIC_PORT_1433}:1433
    restart: always
    volumes:
      - /home/dockervolumes/${CONTAINER_NAME}/mssql:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
