version: '3.7'

services:
  omada-controller:
    # Limits
    cpus: 1.0
    mem_reservation: "2048M"
    mem_limit: "4096M"
    
    image: mbentley/omada-controller:${OMADA_IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    networks:
      - omada-net
    volumes:
      - '/home/dockervolumes/${CONTAINER_NAME}/data:/opt/tplink/EAPController/data'
      - '/home/dockervolumes/${CONTAINER_NAME}/work:/opt/tplink/EAPController/work'
      - '/home/dockervolumes/${CONTAINER_NAME}/logs:/opt/tplink/EAPController/logs'
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - TZ=Europe/Berlin
    ports:
      - '8088:8088'
      - '8043:8043'
      - '8843:8843'
      - '29810:29810/udp'
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
      - '29814:29814'

networks:
  omada-net:
    name: omada-net
